name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Checkout distribution repository
      uses: actions/checkout@v2
      with:
        repository: graytoowolf/plugins-dist
        path: '.dist'
        token: ${{ secrets.GH_TOKEN }}
    - name: Download nano
      run: ./download-nano.ps1
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: ./nano
      env:
        RUST_LOG: info
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: ./publish.ps1
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
