name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Checkout distribution repository
      uses: actions/checkout@v2
      with:
        repository: graytoowolf/plugins-dist
        path: '.dist'
        token: ${{ secrets.GH_TOKEN }}
    # 添加 Node.js 设置
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        version: 8.15.9
    - name: Download nano
      run: ./download-nano.ps1
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: ./nano
      env:
        RUST_LOG: info
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: ./publish.ps1
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Upload qiniu
      run: |
        mkdir -p qiniu/plugins
        cp -r .dist/. qiniu/plugins
        wget https://devtools.qiniu.com/qshell-v2.9.0-linux-386.tar.gz?ref=developer.qiniu.com -O qshell.tar.gz
        tar -zxvf qshell.tar.gz
        ./qshell account ${{ secrets.QINIU_AccessKey }} ${{ secrets.QINIU_SecretKey }} bs
        ./qshell qupload2 --src-dir=./qiniu --bucket=${{ secrets.QINIU_Name }} --overwrite=true --check-exists=true --check-hash=true --skip-fixed-strings=.git
