name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Checkout distribution repository
      uses: actions/checkout@v2
      with:
        repository: graytoowolf/plugins-dist
        path: '.dist'
        token: ${{ secrets.GH_TOKEN }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7.26.0
    - name: Download nano
      run: ./download-nano.ps1
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: ./nano
      env:
        RUST_LOG: info
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: ./publish.ps1
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    # 设置 AWS 凭证
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        # 设置 AWS 凭证过期时间，默认为 1 小时
        expires-in: 3600

    # 将目录同步到 S3
    - name: Sync to S3
      run: |
        mkdir -p qiniu/plugins
        cp -r .dist/. qiniu/plugins
        aws s3 sync ./qiniu/plugins s3://${{ secrets.AWS_S3_Name }}/plugins --delete --exclude ".git/*"
